### ISSUE TITLE
Preset Usage?

### ISSUE THREAD

**Issue by MRobi1** [muxa/esphome-wled-output#1]
I've built a garage door controller in ESPHome.
I currently have an automation running in Home Assistant that sets WLED presets based on the state of the garage door. [LED Effects like this](https://youtu.be/M8xCgQUihd8)

```
      - if:
          - condition: state
            entity_id: light.wled_mikes_door
            state: "off"
        then:
          - service: light.turn_on
            data: {}
            target:
              entity_id: light.wled_mikes_door
      - service: select.select_option
        target:
          entity_id: select.wled_preset
        data:
          option: " Mike red flash"
```

I'd love to be able to take HA out of the equation and control the presets directly from ESPHome. This way if HA is down for whatever reason, the light automation could still be run.
In WLED There are 2 segments (for 2 doors) and presets used for the effects.

Is this something that can be done with this component?
